site_name: Tools in Python
dev_addr: 127.0.0.1:9999
repo_name: GitHub
repo_url: https://github.com/eastsunrise/tools-py
edit_uri: edit/master/docs
use_directory_urls: false
nav:
  - Home: index.md
theme:
  name: mkdocs
  navigation_depth: 5
extra_javascript:
  - js/common.js
extra_css:
  - css/common.css