SELECT A.COLUMN_NAME, A.DATA_TYPE, A.DATA_LENGTH, A.NULLABLE, B.COMMENTS, E.CONSTRAINT_NAME
FROM user_tab_cols A
         LEFT JOIN user_col_comments B ON A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME
         LEFT JOIN (SELECT C.CONSTRAINT_NAME, C.TABLE_NAME, D.COLUMN_NAME
                    FROM user_constraints C
                             LEFT JOIN user_cons_columns D ON C.CONSTRAINT_NAME = D.CONSTRAINT_NAME
                    WHERE C.CONSTRAINT_TYPE = 'P') E ON A.TABLE_NAME = E.TABLE_NAME AND A.COLUMN_NAME = E.COLUMN_NAME
WHERE A.TABLE_NAME = '{{ TABLE_NAME }}'
ORDER BY A.COLUMN_ID