version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(threadName)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    maxBytes: 10485760
    encoding: utf-8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/error.log
    maxBytes: 10485760
    encoding: utf-8
loggers:
  default:
    level: INFO
    handlers: [console]
    propagate: False
root:
  level: DEBUG
  handlers: [console, info_file]